// TODO: Falta agregar links de imagenes para que no lance error
let productos = [
    {
        id: "1",
        cod_prod: "P001",
        name: "Ramo de rosas lilas",
        price: 12500,
        desc: "Clásico y elegante ramo extendido con 18 rosas ecuatorianas lilas, desespinadas, de tallo largo, envueltas en un delicado papel metalizado y hermoso moño de cinta.",
        short_desc: "18 ecuatorianas rosas lilas",
        stock_actual: 20,
        stock_min: 5,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/1708/10439/800/10439.jpg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/1708/10438/800/10438.jpg",
                    "https://storage.googleapis.com/rosalinda-productos/producto/1708/10437/800/10437.jpg",
                     "https://storage.googleapis.com/rosalinda-productos/producto/1708/10435/800/10435.jpg"]
    },
    {
        id: "2",
        cod_prod: "P002",
        name: "Ramo de rosas rojas",
        price: 17500,
        desc: "Hermoso y elegante ramo circular con 24 rosas ecuatorianas de color rojo, desespinadas, de tallo largo, envueltas en un delicado papel metalizado con un hermoso moño.",
        short_desc: "24 rosas ecuatorianas rojas",
        stock_actual: 15,
        stock_min: 3,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/1076/10557/800/10557.jpg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/1076/10559/800/10559.jpg",
                    "https://storage.googleapis.com/rosalinda-productos/producto/1076/10560/800/10560.jpg",
                    "https://storage.googleapis.com/rosalinda-productos/producto/1076/10558/800/10558.jpg"]
    },
    {
        id: "3",
        cod_prod: "P003",
        name: "Ángel blanco en Ramo",
        price: 9800,
        desc: "Consta de rosas ecuatorianas blancas, cuyos pétalos transmiten pureza y sofisticación, junto con un vibrante mix de astromelias y para acompañar vara de oro en un vibrante color amarillo. Cada flor ha sido seleccionada para garantizar una combinación armoniosa y cautivadora.",
        short_desc: "Mix de rosas blancas, astromelias y vara de oro",
        stock_actual: 18,
        stock_min: 4,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/1139/17488/800/17488.jpeg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/1139/17486/800/17486.jpg",
                    "https://storage.googleapis.com/rosalinda-productos/producto/1139/17485/800/17485.jpg",
                    "https://storage.googleapis.com/rosalinda-productos/producto/1139/17487/800/17487.jpg"]
    },
    {
        id: "4",
        cod_prod: "P004",
        name: "Ramo de rosas azules",
        price: 12500,
        desc: "Clásico y elegante ramo extendido con 18 rosas ecuatorianas azules, desespinadas, de tallo largo, envueltas en un delicado papel metalizado y hermoso moño de cinta.",
        short_desc: "18 rosas ecuatorianas azules",
        stock_actual: 12,
        stock_min: 3,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/11/12458/800/12458.jpg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/11/12461/800/12461.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/11/12460/800/12460.jpg",
                    "https://storage.googleapis.com/rosalinda-productos/producto/11/12462/800/12462.jpg"]
    },
    {
        id: "5",
        cod_prod: "P005",
        name: "Florero mix de flores de temporada",
        price: 20000,
        desc: "Exclusivo arreglo floral para regalar con diseño Rosalinda confeccionado en florero de vidrio, compuesto por nuestra mejor selección de flores frescas de temporada, y decorado con un pequeño moño de rafia.",
        short_desc: "Florero mix",
        stock_actual: 25,
        stock_min: 6,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/2227/18452/800/18452.jpg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/2227/18450/800/18450.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/2227/18453/800/18453.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/2227/18455/800/18455.jpg"]
    },
    {
        id: "6",
        cod_prod: "P006",
        name: "Florero negro mediano - Rosas",
        price: 25000,
        desc: "Arreglo floral confeccionado con 10 rosas ecuatorianas de color rojo, mini claveles en tonos fucsia y rosados, y un follaje de ruscus en una encantadora base de cerámica nnegra con detalle de líneas diagonales negras.",
        short_desc: "Florero negro con 10 rosas ecuatorianas",
        stock_actual: 10,
        stock_min: 2,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/2241/15348/800/15348.jpg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/2241/13794/800/13794.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/2241/13796/800/13796.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/2241/15347/800/15347.jpg"]
    },
    {
        id: "7",
        cod_prod: "P007",
        name: "Arreglo floral con liliums rojos e hypericum rosado",
        price: 30000,
        desc: "Este arreglo floral confeccionado con unos hermosos liliums de color rojo, y detalles de hypericum rosado y ruscus, es realizado en un lindo balde metálico con un acabado de pintura envejecida que genera una sensación campestre. Un conjunto lleno de armonía y belleza. ",
        short_desc: "¡Sorprende con la belleza y elegancia de los liliums! ",
        stock_actual: 8,
        stock_min: 2,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/2188/13461/800/13461.jpg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/2188/13462/800/13462.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/2188/13464/800/13464.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/2188/13465/800/13465.jpg"]
    },
    {
        id: "8",
        cod_prod: "P008",
        name: "Arreglo floral en canasto con gerberas, rosas, minirosas y astromelias amarillas",
        price: 13500,
        desc: "Linda composición de flores que reúne en tonos amarillos 5 gerberas, 10 rosas ecuatorianas, astromelias y minirosas, acompañado de un follaje de palmilla sobre un canasto de mimbre tejido en dos tonos, el cuál se convierte en un perfecto agregado de utilidad en la decoración del hogar.",
        short_desc: "Un obsequio lleno de vida y belleza.",
        stock_actual: 14,
        stock_min: 3,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/1760/11658/800/11658.jpg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/1760/11659/800/11659.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/1760/11660/800/11660.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/1760/11662/800/11662.jpg"]
    },
    {
        id: "9",
        cod_prod: "P009",
        name: "Corona de Flores blancas",
        price: 149900,
        desc: "Sobria corona fúnebre que está confeccionada con hermosas flores blancas de temporada como gerberas, rosas y gypsophilas, con un follaje de avellano y palmilla dispuesto sobre un atril.",
        short_desc: "Esta ofrenda floral es un perfecto símbolo de cariño y apoyo.",
        stock_actual: 30,
        stock_min: 5,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/2156/13300/800/13300.jpg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/2156/13304/800/13304.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/2156/13302/800/13302.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/2156/13303/800/13303.jpg"]
    },
    {
        id: "10",
        cod_prod: "P010",
        name: "Corona con rosas",
        price: 159900,
        desc: "Hermosa y elegante composición floral confeccionada con rosas ecuatorianas blancas y lilas, en conjunto con un follaje de palmilla, avellano y gypsophilia.",
        short_desc: "Una despedida por siempre recordada.",
        stock_actual: 20,
        stock_min: 5,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/1961/11951/800/11951.jpg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/1961/11949/800/11949.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/1961/11947/800/11947.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/1961/11950/800/11950.jpg"]
    },
    {
        id: "11",
        cod_prod: "P011",
        name: "Ramo con calas y rosas blancas",
        price: 39900,
        desc: "Está confeccionado con 5 calas blanco, 5 rosas ecuatorianas blanco, 5 vara de oro, 5 astromelias blanco y 5 maules verdes, envuelto en papeles metalizados y mallas de los mismos tonos y un moño de rafia. ",
        short_desc: "¡Lindo ramo diseñado con calas,  rosas y astromelias!",
        stock_actual: 6,
        stock_min: 2,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/649/7256/800/7256.jpg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/649/7259/800/7259.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/649/7260/800/7260.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/649/7257/800/7257.jpg"]
    },
    {
        id: "12",
        cod_prod: "P012",
        name: "Arreglo floral en sombrerero",
        price: 42900,
        desc: "Clarita Blanco es un delicado y sobrio arreglo floral confeccionado con 9 rosas ecuatorianas blanco, limonium, vara de oro y ruscus, todo esto sobre una base de sombrerero.",
        short_desc: "Este arreglo llenará de luz y paz a esa persona especial.",
        stock_actual: 40,
        stock_min: 10,
        image: "https://storage.googleapis.com/rosalinda-productos/producto/2461/18152/800/18152.jpg",
        other_images: ["https://storage.googleapis.com/rosalinda-productos/producto/2461/18150/800/18150.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/2461/18153/800/18153.jpg", 
                    "https://storage.googleapis.com/rosalinda-productos/producto/2461/18154/800/18154.jpg"]
    }
];
